version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  app:
    build:
      context: ./ # caminho onde está o Dockerfile da sua app
    container_name: app
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
